export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const SUCCESS_LOAD_USER_FROM_LOCALSTORAGE = 'SUCCESS_LOAD_USER_FROM_LOCALSTORAGE';

export const GET_MY_BUDGETS = 'GET_MY_BUDGETS';
export const GET_MY_BUDGETS_SUCCESS = 'GET_MY_BUDGETS_SUCCESS';
export const GET_MY_BUDGETS_FAIL = 'GET_MY_BUDGETS_FAIL';
export const SET_CURRENT_BUDGET = 'SET_CURRENT_BUDGET';

export const GET_MY_POCKETS = 'GET_MY_POCKETS';
export const GET_MY_POCKETS_SUCCESS = 'GET_MY_POCKETS_SUCCESS';
export const GET_MY_POCKETS_FAIL = 'GET_MY_POCKETS_FAIL';

export const GET_LIST__OF_MY_CATEGORIES = 'GET_LIST__OF_MY_CATEGORIES';
export const GET_LIST__OF_MY_CATEGORIES_SUCCESS = 'GET_LIST__OF_MY_CATEGORIES_SUCCESS';
export const GET_LIST__OF_MY_CATEGORIES_FAIL = 'GET_LIST__OF_MY_CATEGORIES_FAIL';

export const GET_TRANSACTIONS_BY_BUDGET_ID = 'GET_TRANSACTIONS_BY_BUDGET_ID';
export const SAVE_ALL_TRANSACTION_OF_BUDGET = 'SAVE_ALL_TRANSACTION_OF_BUDGET';

export const SEND_NEW_TRANSACTION = 'SEND_NEW_TRANSACTION';
